package com.powersurgepub.clubplanner.view;

  import com.powersurgepub.clubplanner.model.*;
  import com.powersurgepub.psdatalib.ui.*;
  import java.awt.*;
  import javax.swing.*;
 
/**
 A panel displaying some of an item's fields, and allowing the user to modify those fields.
 
 Generated by PSTextMerge using item-panel.java.

 @author Herb Bowie
 */
public class ClubEventPanel1
		extends
			JPanel {
	

  /*
   Following code generated by PSTextMerge using:
 
     template:  item-panel-definitions.java
     data file: fields.xls
   */
 

  private JLabel    fileNameLabel    = new JLabel("File Name:", JLabel.LEFT);
  private JTextField fileNameJTextField = new JTextField();

  private JLabel    whatLabel    = new JLabel("What:", JLabel.LEFT);
  private JTextField whatJTextField = new JTextField();

  private JLabel    whenLabel    = new JLabel("When:", JLabel.LEFT);
  private JTextField whenJTextField = new JTextField();

  private JLabel    ymdLabel    = new JLabel("YMD:", JLabel.LEFT);
  private JLabel ymdJLabel = new JLabel();

  private JLabel    typeLabel    = new JLabel("Type:", JLabel.LEFT);
  private TextSelector typeTextSelector = new TextSelector();

  private JLabel    whereLabel    = new JLabel("Where:", JLabel.LEFT);
  private JTextField whereJTextField = new JTextField();

  private JLabel    whoLabel    = new JLabel("Who:", JLabel.LEFT);
  private JTextField whoJTextField = new JTextField();

  private     JLabel              bottomFiller   = new JLabel("");

  private     boolean             modified = false;

	private     GridBagger          gb = new GridBagger();

  /**
   A constructor without any arguments.
   */
  public ClubEventPanel1() {
 
    gb.startLayout (this, 2, 99);
    gb.setByRows(true);
		gb.setDefaultColumnWeight (0.5);
		gb.setDefaultRowWeight (0.0);
		gb.setAllInsets (4);
    gb.setFill(GridBagConstraints.HORIZONTAL);
    gb.setAnchor(GridBagConstraints.WEST);


  /*
   Following code generated by PSTextMerge using:
 
     template:  item-panel-layout.java
     data file: fields.xls
   */
 
    fileNameLabel.setLabelFor(fileNameJTextField);
    gb.setColumnWeight(0.0);
    gb.add(fileNameLabel);
    gb.add(fileNameJTextField);
    whatLabel.setLabelFor(whatJTextField);
    gb.setColumnWeight(0.0);
    gb.add(whatLabel);
    gb.add(whatJTextField);
    whenLabel.setLabelFor(whenJTextField);
    gb.setColumnWeight(0.0);
    gb.add(whenLabel);
    gb.add(whenJTextField);
    ymdLabel.setLabelFor(ymdJLabel);
    gb.setColumnWeight(0.0);
    gb.add(ymdLabel);
    gb.add(ymdJLabel);
    typeLabel.setLabelFor(typeTextSelector);
    gb.setColumnWeight(0.0);
    gb.add(typeLabel);
    gb.add(typeTextSelector);
    whereLabel.setLabelFor(whereJTextField);
    gb.setColumnWeight(0.0);
    gb.add(whereLabel);
    gb.add(whereJTextField);
    whoLabel.setLabelFor(whoJTextField);
    gb.setColumnWeight(0.0);
    gb.add(whoLabel);
    gb.add(whoJTextField);

    gb.setWidth(2);
    gb.setFill(GridBagConstraints.BOTH);
    gb.setColumnWeight(1.0);
    gb.setRowWeight(1.0);
    gb.add(bottomFiller);
 
  }
 

  /*
   Following code generated by PSTextMerge using:
 
     template:  item-panel-display.java
     data file: fields.xls
   */
  public void display (ClubEvent clubEvent) {
 
    modified = false;
 
    if (clubEvent.hasFileName()) {
      fileNameJTextField.setText (clubEvent.getFileName().toString());
    } else {
      fileNameJTextField.setText ("");
    }
    if (clubEvent.hasWhat()) {
      whatJTextField.setText (clubEvent.getWhat().toString());
    } else {
      whatJTextField.setText ("");
    }
    if (clubEvent.hasWhen()) {
      whenJTextField.setText (clubEvent.getWhen().toString());
    } else {
      whenJTextField.setText ("");
    }
    if (clubEvent.hasYmd()) {
      ymdJLabel.setText (clubEvent.getYmd().toString());
    } else {
      ymdJLabel.setText ("");
    }
    if (clubEvent.hasType()) {
      typeTextSelector.setText (clubEvent.getType().toString());
    } else {
      typeTextSelector.setText ("");
    }
    if (clubEvent.hasWhere()) {
      whereJTextField.setText (clubEvent.getWhere().toString());
    } else {
      whereJTextField.setText ("");
    }
    if (clubEvent.hasWho()) {
      whoJTextField.setText (clubEvent.getWho().toString());
    } else {
      whoJTextField.setText ("");
    }
 
  }


  /*
   Following code generated by PSTextMerge using:
 
     template:  item-panel-mod.java
     data file: fields.xls
   */
 
  public boolean modIfChanged (ClubEvent clubEvent) {
 
    if (! clubEvent.getFileNameAsString().equals (fileNameJTextField.getText())) {
      clubEvent.setFileName(fileNameJTextField.getText());
      modified = true;
    }
    if (! clubEvent.getWhatAsString().equals (whatJTextField.getText())) {
      clubEvent.setWhat(whatJTextField.getText());
      modified = true;
    }
    if (! clubEvent.getWhenAsString().equals (whenJTextField.getText())) {
      clubEvent.setWhen(whenJTextField.getText());
      modified = true;
    }
    if (! clubEvent.getYmdAsString().equals (ymdJLabel.getText())) {
      clubEvent.setYmd(ymdJLabel.getText());
      modified = true;
    }
    if (! clubEvent.getTypeAsString().equals (typeTextSelector.getText())) {
      clubEvent.setType(typeTextSelector.getText());
      modified = true;
    }
    if (! clubEvent.getWhereAsString().equals (whereJTextField.getText())) {
      clubEvent.setWhere(whereJTextField.getText());
      modified = true;
    }
    if (! clubEvent.getWhoAsString().equals (whoJTextField.getText())) {
      clubEvent.setWho(whoJTextField.getText());
      modified = true;
    }

    return modified;
 
  }


  /*
   Following code generated by PSTextMerge using:
 
     template:  item-panel-get.java
     data file: fields.xls
   */
 

  /**
    Returns the file name for this club event.
 
    @return The file name for this club event.
   */
  public JTextField getFileNameJTextField () {
    return fileNameJTextField;
  }

  /**
    Returns the what for this club event.
 
    @return The what for this club event.
   */
  public JTextField getWhatJTextField () {
    return whatJTextField;
  }

  /**
    Returns the when for this club event.
 
    @return The when for this club event.
   */
  public JTextField getWhenJTextField () {
    return whenJTextField;
  }

  /**
    Returns the ymd for this club event.
 
    @return The ymd for this club event.
   */
  public JLabel getYmdJLabel () {
    return ymdJLabel;
  }

  /**
    Returns the type for this club event.
 
    @return The type for this club event.
   */
  public TextSelector getTypeTextSelector () {
    return typeTextSelector;
  }

  /**
    Returns the where for this club event.
 
    @return The where for this club event.
   */
  public JTextField getWhereJTextField () {
    return whereJTextField;
  }

  /**
    Returns the who for this club event.
 
    @return The who for this club event.
   */
  public JTextField getWhoJTextField () {
    return whoJTextField;
  }

}
