package com.powersurgepub.clubplanner.view;

  import com.powersurgepub.clubplanner.*;
  import com.powersurgepub.clubplanner.model.*;
  import com.powersurgepub.psdatalib.clubplanner.*;
  import com.powersurgepub.psdatalib.ui.*;
  import java.awt.*;
  import javax.swing.*;
 
/**
 A panel displaying some of an item's fields, and allowing the user to modify those fields.
 
 Generated by PSTextMerge using item-panel.java.

 @author Herb Bowie
 */
public class ClubEventPanel5
		extends
			JPanel {
	

  /*
   Following code generated by PSTextMerge using:
 
     template:  item-panel-definitions.java
     data file: fields.xls
   */
 

  private JLabel    notesLabel    = new JLabel("Notes:", JLabel.LEFT);
  private JScrollPane notesScrollPane = new javax.swing.JScrollPane();
  private JTextArea notesJTextArea = new JTextArea();

  private     JLabel              bottomFiller   = new JLabel("");

  private     boolean             modified = false;

	private     GridBagger          gb = new GridBagger();

  /**
   A constructor without any arguments.
   */
  public ClubEventPanel5() {
 
    gb.startLayout (this, 4, 99);
    gb.setByRows(true);
		gb.setDefaultColumnWeight (0.5);
		gb.setDefaultRowWeight (0.0);
		gb.setAllInsets (4);
    gb.setFill(GridBagConstraints.HORIZONTAL);
    gb.setAnchor(GridBagConstraints.NORTHWEST);


  /*
   Following code generated by PSTextMerge using:
 
     template:  item-panel-layout.java
     data file: fields.xls
   */
 

		// Panel Layout for Notes
    notesLabel.setLabelFor(notesJTextArea);
    gb.setColumnWeight(0.0);
    gb.setWidth(1);
    gb.setTopInset(8);
    gb.add(notesLabel);
    notesJTextArea.setColumns(20);
    notesJTextArea.setLineWrap(true);
    notesJTextArea.setRows(15);
    notesJTextArea.setWrapStyleWord(true);
    notesJTextArea.setToolTipText("One or more blocks of text with information about the event. Each note should be preceded by a line like the following: -- AAUM on Feb 21 via email.");
    notesScrollPane.setViewportView(notesJTextArea);
    gb.setWidth(3);
    gb.setTopInset(4);
    gb.setRowWeight(0.25);
    gb.add(notesScrollPane);

    gb.setWidth(2);
    gb.setFill(GridBagConstraints.BOTH);
    gb.setColumnWeight(1.0);
    gb.setRowWeight(0.1);
    gb.add(bottomFiller);
 
  }
 

  /*
   Following code generated by PSTextMerge using:
 
     template:  item-panel-display.java
     data file: fields.xls
   */
  public void display (ClubEvent clubEvent) {
 
    modified = false;
 
    if (clubEvent.hasNotes()) {
      notesJTextArea.setText (clubEvent.getNotes().toString());
    } else {
      notesJTextArea.setText ("");
    }
    notesJTextArea.setCaretPosition(0);
 
  }


  /*
   Following code generated by PSTextMerge using:
 
     template:  item-panel-mod.java
     data file: fields.xls
   */
 
  public boolean modIfChanged (ClubEvent clubEvent) {
 
    if (! clubEvent.getNotesAsString().equals (notesJTextArea.getText())) {
      clubEvent.setNotes(notesJTextArea.getText());
      modified = true;
    }

    return modified;
 
  }


  /*
   Following code generated by PSTextMerge using:
 
     template:  item-panel-get.java
     data file: fields.xls
   */
 

  /**
    Returns the notes for this club event.
 
    @return The notes for this club event.
   */
  public JTextArea getNotesJTextArea () {
    return notesJTextArea;
  }

}
