/*
 * Copyright 2012 - 2014 Herb Bowie
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.powersurgepub.clubplanner.model;

  import com.powersurgepub.psdatalib.clubplanner.*;
  import com.powersurgepub.psdatalib.psdata.*;
  import com.powersurgepub.psdatalib.pslist.*;
  import com.powersurgepub.psdatalib.pstags.*;
  import com.powersurgepub.psfiles.*;
  import com.powersurgepub.psutils.*;
  import java.io.*;
  import java.util.*;
  import javax.swing.table.*;

/**
 A single class that manages multiple lists of items and keeps the lists
 appropriately synchronized. The first such list is a raw list of all items.
 The second such list is a filtered, sorted list of item proxies that point
 back to the real items in the raw list. <p>
 
    This item master list class generated by PSTextMerge using: <p>
 
     template:  master-list.java <p>
     data file: /Users/hbowie/Java/projects/nbproj/clubplanner/javagen/fields.xls

 @author Herb Bowie
 */
public class ClubEventList
    extends
      AbstractTableModel
    implements
      DataSource,
      PSList,
      TaggableList {
 
  private String          title = "Club Event List";
 
  private FileSpec        fileSpec = null;
 
  private RecordDefinition recDef = new RecordDefinition();
 
  private List<ClubEvent>            list = new ArrayList();
  private List<ClubEventProxy>       proxyList = new ArrayList();
 
  private Comparator      comparator = new ClubEventDefaultComparator();
  private PSItemFilter    itemFilter = null;
 
  private int             findIndex = -1;
  private boolean         findMatch = false;
 
  private TagsList        tagsList = new TagsList();
  private TagsModel       tagsModel = new TagsModel();
 
  private int             dataSourceIndex = 0;
 
  /** Log used to record events. */
  private    Logger             log;
 
  /** Should all data be logged (or only data preceding significant events(? */
  private    boolean            dataLogging = false;
 
  /** Data to be logged. */
  private    LogData            logData;
 
  /** Debug instance. */
  private		 Debug							debug = new Debug (false);
 
  /** Identifier used to identify this reader in the log. */
  private    String             fileId;
 
  /** Path to the original source file (if any). */
  private		 String							dataParent;
 

  /*
   Following code generated by PSTextMerge using:
 
     template:  master-list-columns.java
     data file: /Users/hbowie/Java/projects/nbproj/clubplanner/javagen/fields.xls
   */
 
 private int[] columns = new int[] {
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54,
      -1 };
 
  /**
   List constructor with no arguments.
   */
  public ClubEventList () {
    tagsList.registerValue("");
    for (int i = 0; i < getColumnCount(); i++) {
      recDef.addColumn(getColumnName(getC(i)));
    }
    log = Logger.getShared();
  }
 
  /**
   Initialize the list with no items in the list.
  */
  public void initialize() {
    list = new ArrayList();
    proxyList = new ArrayList();
    tagsList = new TagsList();
    tagsModel = new TagsModel();
    tagsList.registerValue("");
    comparator = new ClubEventDefaultComparator();
    itemFilter = null;
  }
 
  public void setComparator (Comparator comparator) {
    if (comparator == null) {
      this.comparator = new ClubEventDefaultComparator();
    }
    else
    if (comparator instanceof PSItemComparator) {
      PSItemComparator itemComparator = (PSItemComparator)comparator;
      if (itemComparator.getNumberOfFields() == 0) {
        this.comparator = new ClubEventDefaultComparator();
      } else {
        this.comparator = comparator;
      }
    } else {
      this.comparator = new ClubEventDefaultComparator();
    }
    reloadProxyList();
    fireTableDataChanged();
  }
 
  public Comparator getComparator() {
    return comparator;
  }
 
  public TagsList getTagsList () {
    return tagsList;
  }

  public TagsModel getTagsModel () {
    return tagsModel;
  }
 
  /**
   Sets a data filter to be used to select desired output records.
 
   @param inputFilter Desired output filter.
   */
  public void setInputFilter (PSItemFilter inputFilter) {
    this.itemFilter = inputFilter;
    reloadProxyList();
    fireTableDataChanged();
  }
 
  public void reloadProxyList() {
    proxyList = new ArrayList();
    for (int i = 0; i < list.size(); i++) {
      addToProxyList(i);
    }
  }
 
  /**
   Set the data source, stored in the root node of the TagsModel tree.
 
   @param source The file or folder from which the data is taken.
  */
  public void setSource (FileSpec fileSpec) {
    this.fileSpec = fileSpec;
    tagsModel.setSource(fileSpec.getFile());
  }
 
  /**
   Get the data source, stored in the root node of the TagsModel tree.
 
   @return The file or folder from which the data is taken.
  */
  public FileSpec getSource () {
    return fileSpec;
  }
 
  public void setTitle (String title) {
    this.title = title;
  }

  public String getTitle () {
    return title;
  }
 
  /**
   Return the number of columns.
   */
  public int getColumnCount () {
    return ClubEvent.getColumnCount();
  }
 
  public String getColumnName (int columnIndex) {
    return ClubEvent.getColumnName (getC(columnIndex));
  }

  public Class getColumnClass (int columnIndex) {
    return ClubEvent.getColumnClass (getC(columnIndex));
  }
 
  /**
   Get the column number assigned to a particular field name.
 
   @param columnName The name of the column. Case and word separation are
                     not significant.
 
   @return The column number (with the first starting at zero), or -1
           if the field name could not be found.
  */
  public int getColumnNumber (String columnName) {
    String commonName = StringUtils.commonName(columnName);
    boolean found = false;
    int i = 0;
    while (i < getColumnCount() && (! found)) {
      found = commonName.equals(ClubEvent.getCommonName(getC(i)));
      if (! found) {
        i++;
      }
    }
    if (! found) {
      return -1;
    } else {
      return i;
    }
  }
 
  /**
   Return the record definition for this list
 
   @return The record definition, or null if no record defined yet.
   */
  public RecordDefinition getRecDef() {
    return recDef;
  }
 
  /**
	 Returns a List containing the names of all the fields
	 stored in the data set.
	
	 @return Proper names of all the fields.
   */
  public List getNames() {
    ArrayList names = new ArrayList();
    for (int i = 0; i < getColumnCount(); i++) {
      names.add(getColumnName(getC(i)));
    }
    return names;
  }
 
  /**
   Return the size of the total list, without any filtering.
   */
  public int totalSize() {
    return list.size();
  }
 
  /**
   Return the size of the filtered list.
 
   @return The size of the filtered list.
  */
  public int size() {
    return proxyList.size();
  }

  /**
   Return the number of rows in the table.
   */
  public int getRowCount() {
    return size();
  }
 
  /**
   Return the column value of the item at the specified index.
   */
  public String getValueAt (int rowIndex, int columnIndex) {
    ClubEvent item = get(rowIndex);
    if (item == null) {
      return "";
    } else {
      Object columnValue = item.getColumnValue(getC(columnIndex));
      if (columnValue == null) {
        return "";
      } else {
        return columnValue.toString();
      }
    }
  } // end method getValueAt
 
  public int getColumnWidth (int columnIndex) {
    return ClubEvent.getColumnWidth(getC(columnIndex));
  }
 
  /**
   Translate the column index used in the table model to the column index
   used in the master record definition.
   */
  private int getC (int columnIndex) {
    if (columnIndex < 0 || columnIndex >= columns.length) {
      return -1;
    } else {
      return columns[columnIndex];
    }
  }
 
  /**
   Get the item at the specified index in the sorted, filtered list.
 
   @param index Indicates the desired position within the sorted, filtered list.
 
   @return The item at the desired index, or null if the index is out
           of bounds.
  */
  public ClubEvent get (int index) {
    if (index >= 0 && index < size()) {
      return proxyList.get(index).getItem(list);
    } else {
      return null;
    }
  } // end method get (int)
 
  /**
   Get the item at the specified index in the raw, unfiltered list.
 
   @param index Indicates the desired position within the raw, unfiltered list.
 
   @return The item at the desired index, or null if the index is out
           of bounds.
  */
  public ClubEvent getUnfiltered (int index) {
    if (index >= 0 && index < totalSize()) {
      return list.get(index);
    } else {
      return null;
    }
  } // end method getUnfiltered (int)
 
  public ClubEventPositioned positionUsingNode (TagsNode node) {
    ClubEventPositioned position = new ClubEventPositioned();
    position.setClubEvent ((ClubEvent)node.getTaggable());
    position.setTagsNode (node);
    findInternalBySortKey (position.getClubEvent());
    position.setIndex (findIndex);
    position.setNavigator (ClubEventPositioned.NAVIGATE_USING_TREE);
    return position;
  }
 
  /**
   Add a new ClubEvent to the list. Maintain the list in ascending sequence
   by the ClubEvent key.
 
   @param newClubEvent
   @return A positioned ClubEvent composed of the resulting ClubEvent and an index
           pointing to its resulting position in the list.
   */
  public ClubEventPositioned add (ClubEvent newClubEvent) {
 
    int listIndex = list.size();
    list.add(newClubEvent);
    addToProxyList(listIndex);
    tagsList.add  (newClubEvent);
    tagsModel.add (newClubEvent);
    return new ClubEventPositioned (newClubEvent, findIndex);
  } // end add method
 
  private void addToProxyList (int i) {
    ClubEvent clubEvent = list.get(i);
    /* System.out.println (
        "ClubEventList.addToProxyList "
        + " # "
        + String.valueOf(i)
        + " : "
        + clubEvent.toString()); */
    if (itemSelected(clubEvent)) {
      /* System.out.println("  item selected");
      System.out.println("  size of proxy list = " + String.valueOf(size()));
      if (size() > 0) {
        System.out.println ("  item at end of list = " + get(size() - 1).toString());
      } */
      ClubEventProxy clubEventProxy = new ClubEventProxy(i);
      findIndex = size();
      if (size() == 0) {
        // If this is the first ClubEvent being added to the proxy list,
        // simply add the proxy to the list
        proxyList.add(clubEventProxy);
      }
      else
      if (comparator.compare (get(size() - 1), clubEvent) < 0) {
        // If the new item has a key higher than the highest item in the
        // collection, simply add the new item to the end
        // (more efficient if an input file happens to be pre-sorted).
        proxyList.add (clubEventProxy);
      } else {
        findInternalBySortKey (clubEvent);
        proxyList.add (findIndex, clubEventProxy);
      }
    }
  }
 
  public boolean itemSelected (ClubEvent clubEvent) {
    if (itemFilter == null) {
      return true;
    } else {
      return itemFilter.selects(clubEvent);
    }
  }

  public ClubEventPositioned modify (ClubEventPositioned modClubEvent) {
    tagsList.modify(modClubEvent.getClubEvent());
    tagsModel.modify(modClubEvent.getClubEvent());
    return modClubEvent;
  }

  /**
   Removes the passed ClubEvent, if it exists in the collection.

   @param position A position containing the ClubEvent to be removed.
 
   @return A position for the next URL following the one just removed.
   */
  public ClubEventPositioned remove (ClubEventPositioned position) {
    int oldIndex = findBySortKey (position.getClubEvent());
    ClubEventPositioned newPosition = position;
    if (findMatch) {
      newPosition = next (position);
      tagsModel.remove (position.getClubEvent());
      tagsList.remove (position.getClubEvent());
      ClubEventProxy proxyRemoved = proxyList.remove(oldIndex);
      ClubEventProxy clubEventProxy = proxyList.get(oldIndex);
      int listIndex = proxyRemoved.getItemIndex();
      int newIndex = newPosition.getIndex();
      if (newIndex >= oldIndex) {
        newPosition.setIndex(newIndex - 1);
      }
      list.remove(listIndex);
      for (int i = 0; i < proxyList.size(); i++) {
        clubEventProxy = proxyList.get(i);
        int itemIndex = clubEventProxy.getItemIndex();
        if (itemIndex > listIndex) {
          itemIndex--;
          clubEventProxy.setItemIndex(itemIndex);
        } // end if item index needs to be adjusted
      } // end for each proxy
    } // end if we found item to be removed
    return newPosition;
  }

  public int findBySortKey (ClubEvent findClubEvent) {
    findInternalBySortKey (findClubEvent);
    if (findMatch) {
      return findIndex;
    } else {
      return -1;
    }
  }

  /**
   Find the appropriate insertion point or match point in the ClubEvent list,
   and use findIndex and findMatch to return the results.

   @param findClubEvent URL we are looking for.
   */
  private void findInternalBySortKey (ClubEvent findClubEvent) {
    int low = 0;
    int high = size() - 1;
    findIndex = 0;
    findMatch = false;
    while (high >= low
        && findMatch == false
        && findIndex < size()) {
      int diff = high - low;
      int split = diff / 2;
      findIndex = low + split;
      int compare = comparator.compare (get(findIndex), findClubEvent);
      if (compare == 0) {
        // found an exact match
        findMatch = true;
      }
      else
      if (compare < 0) {
        // ClubEvent from list is less than the one we're looking for
        findIndex++;
        low = findIndex;
      } else {
        // ClubEvent from list is greater than the one we're looking for
        if (high > findIndex) {
          high = findIndex;
        } else {
          high = findIndex - 1;
        }
      }
    } // end while looking for right position
  } // end findBySortKey method
 

 /**
   Find the matching item, based on its unique key, if it exists in the list.
   This code was generated by PSTextMerge using template master-list-findByUniqueKey.java
   with data file /Users/hbowie/Java/projects/nbproj/clubplanner/javagen/fields.xls.

   @param findClubEvent Master item we are looking for.
   @return Index pointing to the found item, or -1 if not found.
   */
  public int findByUniqueKey (ClubEvent findClubEvent) {
    int index = 0;
    boolean found = false;
    ClubEvent currentClubEvent;
    while ((! found) && (index < size())) {
      currentClubEvent = get (index);
      boolean match = true;
      if (findClubEvent.getWhat() == null
          && currentClubEvent.getWhat() == null) {
        match = true;
      }
      else
      if (findClubEvent.getWhat() == null
          || currentClubEvent.getWhat() == null) {
        match = false;
      } else {
        match =
          (findClubEvent.getWhatAsString().equalsIgnoreCase
            (currentClubEvent.getWhatAsString()));
			}
      if (match) {
        found = true;
      } else {
        index++;
      }
    }
    if (found) {
      return index;
    } else {
      return -1;
    }
  }
 
  public ClubEventPositioned first (ClubEventPositioned position) {
    if (position.navigateUsingList()) {
      return firstUsingList ();
    } else {
      return firstUsingTree ();
    }
  }
 
  public ClubEventPositioned last (ClubEventPositioned position) {
    if (position.navigateUsingList()) {
      return lastUsingList ();
    } else {
      return lastUsingTree ();
    }
  }

  public ClubEventPositioned next (ClubEventPositioned position) {
    if (position.navigateUsingList()) {
      return nextUsingList (position);
    } else {
      return nextUsingTree (position);
    }
  }

  public ClubEventPositioned prior (ClubEventPositioned position) {
    if (position.navigateUsingList()) {
      return priorUsingList (position);
    } else {
      return priorUsingTree (position);
    }
  }

  public ClubEventPositioned firstUsingList () {
    return positionUsingListIndex (0);
  }

  public ClubEventPositioned lastUsingList () {
    return positionUsingListIndex (size() - 1);
  }

  public ClubEventPositioned nextUsingList (ClubEventPositioned position) {
    return (positionUsingListIndex (position.getIndex() + 1));
  }

  public ClubEventPositioned priorUsingList (ClubEventPositioned position) {
    return (positionUsingListIndex (position.getIndex() - 1));
  }

  public ClubEventPositioned positionUsingListIndex (int index) {
    if (index < 0) {
      index = 0;
    }
    if (index >= size()) {
      index = size() - 1;
    }
    ClubEventPositioned position = new ClubEventPositioned();
    position.setIndex (index);
    position.setNavigator (ClubEventPositioned.NAVIGATE_USING_LIST);
    if (index >= 0) {
      position.setClubEvent (get (index));
      position.setTagsNode (position.getClubEvent().getTagsNode());
    }
    return position;
  }

  public ClubEventPositioned firstUsingTree () {
    return positionUsingNode (tagsModel.firstItemNode());
  }

  public ClubEventPositioned lastUsingTree () {
    return positionUsingNode (tagsModel.lastItemNode());
  }

  public ClubEventPositioned nextUsingTree (ClubEventPositioned position) {
    if (position.getTagsNode() == null) {
      return null;
    } else {
      return positionUsingNode
          (tagsModel.nextItemNode(position.getTagsNode()));
    }
  }

  public ClubEventPositioned priorUsingTree (ClubEventPositioned position) {
    if (position.getTagsNode() == null) {
      return null;
    } else {
      return positionUsingNode
          (tagsModel.priorItemNode(position.getTagsNode()));
    }
  }
 
  /**
     Opens the reader for input.
 
     @param inDict A data dictionary to use.
 
     @throws IOException If there is trouble opening a disk file.
   */
  public void openForInput (DataDictionary inDict)
      throws IOException {
    dataSourceIndex = 0;
  }
 
  /**
     Opens the reader for input.
 
     @param inRecDef A record definition to use.
 
     @throws IOException If there is trouble opening a disk file.
   */
  public void openForInput (RecordDefinition inRecDef)
      throws IOException {
    dataSourceIndex = 0;
  }
 
  /**
     Opens the reader for input.
 
     @throws IOException If there is trouble opening a disk file.
   */
  public void openForInput ()
      throws IOException {
    dataSourceIndex = 0;
  }
 
  /**
     Returns the next input data record.
 
     @return Next data record.
 
     @throws IOException If reading from a source that might generate
                         these.
   */
  public DataRecord nextRecordIn ()
      throws IOException {
    if (isAtEnd()) {
      return null;
    } else {
      ClubEvent clubEvent = get(dataSourceIndex);
      dataSourceIndex++;
      return clubEvent.getDataRec();
    }
  }
 
  /**
     Indicates whether there are more records to return.
 
     @return True if no more records to return.
   */
  public boolean isAtEnd() {
    return (dataSourceIndex >= size());
  }
 
  /**
     Returns the sequential record number of the last record returned.
 
     @return Sequential record number of the last record returned via
             nextRecordIn, where 1 identifies the first record.
   */
  public int getRecordNumber () {
    return dataSourceIndex;
  }
 
  /**
     Closes the reader.
 
     @throws IOException If there is trouble closing the file.
   */
  public void close ()
      throws IOException {
 
  }
 
  /**
     Sets a log to be used by the reader to record events.
 
     @param  log A logger object to use.
   */
  public void setLog (Logger log) {
    this.log = log;
  }
 
  /**
     Sets the debug instance to the passed value.
 
     @param debug Debug instance.
   */
  public void setDebug (Debug debug) {
    this.debug = debug;
  }
 
  /**
     Indicates whether all data records are to be logged.
 
     @param  dataLogging True if all data records are to be logged.
   */
  public void setDataLogging (boolean dataLogging) {
    this.dataLogging = dataLogging;
  }
 
  /**
     Sets a file ID to be used to identify this reader in the log.
 
     @param  fileId An identifier for this reader.
   */
  public void setFileId (String fileId) {
    this.fileId = fileId;
    logData.setSourceId (fileId);
  }
 
  /**
     Sets the maximum directory explosion depth.
 
     @param maxDepth Desired directory/sub-directory explosion depth.
   */
  public void setMaxDepth (int maxDepth) {
 
  }
 
  /**
     Retrieves the path to the original source file (if any).
 
     @return Path to the original source file (if any).
   */
  public String getDataParent () {
    return dataParent;
  }
 
  /**
     Returns the reader as some kind of string.
 
     @return String identification of the reader.
   */
  public String toString () {
    return title;
  }

}
