/*
 * Copyright 2015 Herb Bowie
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.powersurgepub.clubplanner;

  import com.powersurgepub.psutils.*;

/**
 A window to obtain variables to be used in creation of a minutes template. 

 @author Herb Bowie
 */
public class MinutesTemplateExportWindow 
    extends javax.swing.JFrame 
        implements
            WindowToManage {
  
  public final static String CLUB_NAME    = "club-name";
  public final static String SECRETARY    = "secretary";
  public final static String MINUTES_DATE = "minutes-date";
  
  private ClubPlanner clubPlanner;

  /**
   Creates new form MinutesTemplateExportWindow
   */
  public MinutesTemplateExportWindow(ClubPlanner clubPlanner) {
    this.clubPlanner = clubPlanner;
    initComponents();
    clubText.setText(UserPrefs.getShared().getPref(CLUB_NAME, "U-M Seattle"));
    secretaryText.setText(UserPrefs.getShared().getPref(SECRETARY, "Secretary"));
    dateText.setText(UserPrefs.getShared().getPref(MINUTES_DATE, ""));
  }
  
  public String getClub() {
    return clubText.getText();
  }
  
  public String getSecretary() {
    return secretaryText.getText();
  }
  
  public String getDate() {
    return dateText.getText();
  }

  /**
   This method is called from within the constructor to initialize the form.
   WARNING: Do NOT modify this code. The content of this method is always
   regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    clubLabel = new javax.swing.JLabel();
    clubText = new javax.swing.JTextField();
    secretaryLabel = new javax.swing.JLabel();
    secretaryText = new javax.swing.JTextField();
    dateLabel = new javax.swing.JLabel();
    dateText = new javax.swing.JTextField();
    doneButton = new javax.swing.JButton();

    setTitle("Mintes Template Export Values");
    getContentPane().setLayout(new java.awt.GridBagLayout());

    clubLabel.setLabelFor(secretaryText);
    clubLabel.setText("Name of Club:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(clubLabel, gridBagConstraints);

    clubText.setColumns(40);
    clubText.setText("U-M Seattle");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(clubText, gridBagConstraints);

    secretaryLabel.setLabelFor(secretaryText);
    secretaryLabel.setText("Name of Secretary: ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(secretaryLabel, gridBagConstraints);

    secretaryText.setColumns(40);
    secretaryText.setText("Secretary");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(secretaryText, gridBagConstraints);

    dateLabel.setText("Date of Meeting:");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(dateLabel, gridBagConstraints);

    dateText.setColumns(40);
    dateText.setText(" ");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(dateText, gridBagConstraints);

    doneButton.setText("OK");
    doneButton.setToolTipText("Click when done entering data");
    doneButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        doneButtonActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
    getContentPane().add(doneButton, gridBagConstraints);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
    UserPrefs.getShared().setPref(CLUB_NAME, clubText.getText());
    UserPrefs.getShared().setPref(SECRETARY, secretaryText.getText());
    UserPrefs.getShared().setPref(MINUTES_DATE, dateText.getText());
    this.setVisible(false);
    clubPlanner.exportMinutesTemplate(
        clubText.getText(),
        secretaryText.getText(), 
        dateText.getText());
  }//GEN-LAST:event_doneButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel clubLabel;
  private javax.swing.JTextField clubText;
  private javax.swing.JLabel dateLabel;
  private javax.swing.JTextField dateText;
  private javax.swing.JButton doneButton;
  private javax.swing.JLabel secretaryLabel;
  private javax.swing.JTextField secretaryText;
  // End of variables declaration//GEN-END:variables
}
