/*
 * PrefsWindow.java
 *
 */

package com.powersurgepub.clubplanner;

  import com.powersurgepub.psdatalib.ui.*;
  import com.powersurgepub.psfiles.*;
  import com.powersurgepub.psutils.*;
  import com.powersurgepub.xos2.*;
  import javax.swing.*;

/**
 *
 * @author  hbowie
 */
public class PrefsWindow extends javax.swing.JFrame {
  
  private ClubPlanner       clubPlanner;

  private XOS               xos = XOS.getShared();
  
  private ProgramVersion    programVersion = ProgramVersion.getShared();
  
  private boolean           setupComplete = false;
  
  private CommonPrefs       commonPrefs;
  private FilePrefs         filePrefs = null;
  
  // private FavoritesPrefs    favoritesPrefs;
  
  /** Creates new form PrefsWindow */
  public PrefsWindow(ClubPlanner clubPlanner) {

    this.clubPlanner = clubPlanner;
    initComponents();
    
    this.setTitle (Home.getShared().getProgramName() + " Preferences");
    this.setBounds (100, 100, 500, 400);

    commonPrefs = CommonPrefs.getShared();
    prefsTabs.addTab("General", commonPrefs);
    
    // favoritesPrefs = new FavoritesPrefs (mainFrame);
    // prefsTabs.addTab("Favorites", favoritesPrefs);
    
    setupComplete = true;
  }
  
  public void setFilePrefs(FilePrefs filePrefs) {
    this.filePrefs = filePrefs;
    prefsTabs.addTab("Files", filePrefs);
  }

  public void savePrefs() {
    commonPrefs.savePrefs();
    if (filePrefs != null) {
      filePrefs.savePrefs();
    }
    // favoritesPrefs.savePrefs();
  }

  /* public FavoritesPrefs getFavoritesPrefs() {
    return favoritesPrefs;
  } */
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prefsTabs = new javax.swing.JTabbedPane();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().add(prefsTabs, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
  WindowMenuManager.getShared().hide(this);
}//GEN-LAST:event_formComponentHidden
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane prefsTabs;
    // End of variables declaration//GEN-END:variables
  
}
