<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
		return =$returnClass$=;
  }
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-duplicate.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
  
  /**
     Duplicates this item, making a deep copy.
   */
  public =$itemclass$= duplicate () {
    =$itemclass$= new=$itemclass$= = new =$itemclass$=();
<?set returnClass = new=$itemclass$= ?>
<?endif?>
<?if =$calc$= == "Calc" ?>
<?else?>
		String =$field&clul$=Str = new String(get=$field&cuul$=AsString());
		new=$itemclass$=.set=$field&cuul$=(=$field&clul$=Str);
<?endif?>
<?loop?>
