<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>

    return found;
  }
<?endif?>
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-find.java"?>
  
  /**
    Check for a search string within the given Club Event item. 
   
    This method generated by PSTextMerge using template =$templatefilename$=.
   
    @param findLower   The search string in all lower case.
    @param findUpper   The search string in all upper case. 
    
    @return True if this item contains the search string 
            in one of its searchable fields. 

   */
  public boolean find (String findLower, String findUpper) {

    boolean found = false;
    int fieldStart = -1;
<?endif?>
<?if =$find$= ?>

    if (get=$field&cuul$=() != null
        && get=$field&cuul$=().length() > 0) {
      fieldStart = StringUtils.indexOfIgnoreCase (findLower, findUpper,
            get=$field&cuul$=(), 0);
      if (fieldStart >= 0) {
        found = true;
      }
    }
<?endif?>
<?loop?>
