<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
      default: return null;
    }
  }
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-getColumnClass.java"?>
<?set columnCount = 0 ?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
  
  /**
     Returns the class of the field at the given column index.
   */
  public static Class getColumnClass (int columnIndex) {
    switch (columnIndex) {
<?endif?>
      case =$field&c_uuu$=_COLUMN_INDEX:
          return =$fieldclass$=.class;
<?set columnCount ++ ?>
<?loop?>
