<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
      default: return 20;
    }
  }
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-getColumnWidth.java"?>
<?set columnCount = 0 ?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
  
  /**
     Returns the field name for the given column index.
   */
  public static int getColumnWidth (int columnIndex) {
    switch (columnIndex) {
<?endif?>
      case =$field&c_uuu$=_COLUMN_INDEX: 
          return =$field&c_uuu$=_COLUMN_WIDTH;
<?set columnCount ++ ?>
<?loop?>
