<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
      default: return null;
    }
  }
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-getCommonName.java"?>
<?set columnCount = 0 ?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
  
  /**
     Returns the common name (all lower case, no word separators)
     for the given column index.
   */
  public static String getCommonName (int columnIndex) {
    switch (columnIndex) {
<?endif?>
      case =$field&c_uuu$=_COLUMN_INDEX: 
          return =$field&c_uuu$=_COMMON_NAME;
<?set columnCount ++ ?>
<?loop?>
