<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
      default: return null;
    }
  }
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-getColumnValue.java"?>
<?set columnCount = 0 ?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
  
  /**
     Returns the value at the given column index.
   */
  public Object getColumnValue (int columnIndex) {
    switch (columnIndex) {
<?endif?>
      case =$field&c_uuu$=_COLUMN_INDEX: 
          return =$field&clul$=;
<?set columnCount ++ ?>
<?loop?>
