<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>

    return hasKey;
  }
<?endif?>
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-haskey-method.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
  
  /**
   Determine if this item has a key.

   @return True if this item has a key.
   */
  public boolean hasKey () {

    boolean hasKey = false;
<?endif?>
<?if =$key$= ?>

		if (get=$field&cuul$=() == null) {
			// No key here
		}
		else
		if (get=$field&cuul$=().toString() == "") {
			// No key here
		} else {
			hasKey = true;
		}
<?endif?>
<?loop?>
