<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
      default: return false;
    }
  }
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-isMarkdownFormat.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
  
  /**
     Indicates whether the field at the given column index should be in Markdown format.
   */
  public static boolean isMarkdownFormat (int columnIndex) {
    switch (columnIndex) {
<?endif?>
<?if "=$markdown$=" ?>
      case =$field&c_uuu$=_COLUMN_INDEX:
          return true;
<?endif?>
<?loop?>
