<?nextrec?>
<?definegroup 1 =$itemclass$= ?>
<?definegroup 2 =$panelno$= ?>
<?ifendgroup 2 ?>
<?if =$currpanelno$= ?>
  
  }
<?endif?>
<?ifendgroup 1 ?>
<?ifnewgroup 1 ?>
<?ifnewgroup 2 ?>
<?set currpanelno = =$panelno$= ?>
<?if =$panelno$= ?>
<?output "../includes/=$itemclass$=Panel=$panelno$=-panel-display.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
  public void display (=$itemclass&cuul$= =$itemclass&clul$=) {
  
    modified = false;
  
<?endif?>
<?endif?>
<?if =$panelno$= ?>
<?if =$panelclass$= == "Link" ?>  
    if (=$itemclass&clul$=.has=$field&cuul$=()) {
      =$field&clul$=JTextArea.setText (=$itemclass&clul$=.get=$field&cuul$=().toString());
    } else {
      =$field&clul$=JTextArea.setText ("");
    }
<?else?>
    if (=$itemclass&clul$=.has=$field&cuul$=()) {
      =$field&clul$==$panelclass$=.setText (=$itemclass&clul$=.get=$field&cuul$=().toString());
    } else {
      =$field&clul$==$panelclass$=.setText ("");
    }
<?endif?>
<?if =$panelclass$= == "JTextArea" ?>
    =$field&clul$==$panelclass$=.setCaretPosition(0);
<?endif?>
<?endif?>
<?loop?>
