<?nextrec?>
<?definegroup 1 =$itemclass$= ?>
<?definegroup 2 =$panelno$= ?>
<?ifendgroup 2 ?>
<?if =$currpanelno$= ?>
<?endif?>
<?ifendgroup 1 ?>
<?ifnewgroup 1 ?>
<?ifnewgroup 2 ?>
<?set currpanelno = =$panelno$= ?>
<?if =$panelno$= ?>
<?output "../includes/=$itemclass$=Panel=$panelno$=-panel-get.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
    
<?endif?>
<?endif?>
<?if =$panelno$= ?>

  /**
    Returns the =$field&c lll$= for this =$itemclass&c lll$=.
   
    @return The =$field&c lll$= for this =$itemclass&c lll$=.
   */
  public =$panelclass$= get=$field&cuul$==$panelclass$= () {
    return =$field&clul$==$panelclass$=;
  }
<?endif?>
<?loop?>
