<?nextrec?>
<?definegroup 1 =$itemclass$= ?>
<?definegroup 2 =$panelno$= ?>
<?ifendgroup 2 ?>
<?if =$currpanelno$= ?>

    return modified;
  
  }
<?endif?>
<?ifendgroup 1 ?>
<?ifnewgroup 1 ?>
<?ifnewgroup 2 ?>
<?set currpanelno = =$panelno$= ?>
<?if =$panelno$= ?>
<?output "../includes/=$itemclass$=Panel=$panelno$=-panel-mod.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
    
  public boolean modIfChanged (=$itemclass$= =$itemclass&clul$=) {
  
<?endif?>
<?endif?>
<?if =$panelno$= ?>
<?if =$panelclass$= == "Link" ?>

    if (! =$itemclass&clul$=.get=$field&cuul$=AsString().equals (=$field&clul$=JTextArea.getText())) {
      =$itemclass&clul$=.set=$field&cuul$=(=$field&clul$=JTextArea.getText());
      modified = true;
    }
<?else?>

    if (! =$itemclass&clul$=.get=$field&cuul$=AsString().equals (=$field&clul$==$panelclass$=.getText())) {
      =$itemclass&clul$=.set=$field&cuul$=(=$field&clul$==$panelclass$=.getText());
      modified = true;
    }
<?endif?>
<?endif?>
<?loop?>
