<?nextrec?>
<?definegroup 1 =$itemclass$= ?>
<?definegroup 2 =$panelno$= ?>
<?ifendgroup 2 ?>
<?ifendgroup 1 ?>
<?ifnewgroup 1 ?>
<?ifnewgroup 2 ?>
<?if =$panelno$= ?>
<?output "../../src/com/powersurgepub/clubplanner/view/=$itemclass$=Panel=$panelno$=.java"?>
package com.powersurgepub.clubplanner.view;

  import com.powersurgepub.clubplanner.model.*;
  import com.powersurgepub.psdatalib.ui.*;
  import java.awt.*;
  import javax.swing.*;
  
/**
 A panel displaying some of an item's fields, and allowing the user to modify those fields.
 
 Generated by PSTextMerge using =$templatefilename$=.

 @author Herb Bowie
 */
public class =$itemclass$=Panel=$panelno$= 
		extends 
			JPanel {
			
<?include "../includes/=$itemclass$=Panel=$panelno$=-panel-definitions.java"?>

  private     JLabel              bottomFiller   = new JLabel("");

  private     boolean             modified = false;

	private     GridBagger          gb = new GridBagger();

  /**
   A constructor without any arguments.
   */
  public =$itemclass$=Panel=$panelno$=() {
  
    gb.startLayout (this, 2, 99);
    gb.setByRows(true);
		gb.setDefaultColumnWeight (0.5);
		gb.setDefaultRowWeight (0.0);
		gb.setAllInsets (4);
    gb.setFill(GridBagConstraints.HORIZONTAL);
    gb.setAnchor(GridBagConstraints.WEST);

<?include "../includes/=$itemclass$=Panel=$panelno$=-panel-layout.java"?>

    gb.setWidth(2);
    gb.setFill(GridBagConstraints.BOTH);
    gb.setColumnWeight(1.0);
    gb.setRowWeight(1.0);    
    gb.add(bottomFiller);
    
  }  
  
<?include "../includes/=$itemclass$=Panel=$panelno$=-panel-display.java"?>

<?include "../includes/=$itemclass$=Panel=$panelno$=-panel-mod.java"?>

<?include "../includes/=$itemclass$=Panel=$panelno$=-panel-get.java"?>

}
<?endif?>
<?endif?>
<?loop?>
