<?nextrec?>
<?definegroup 1 =$itemclass$= ?>
<?definegroup 2 =$panelno$= ?>
<?ifendgroup 2 ?>
<?ifendgroup 1 ?>
<?ifnewgroup 1 ?>
<?ifnewgroup 2 ?>
<?if =$panelno$= ?>
<?output "../../src/com/powersurgepub/clubplanner/view/=$itemclass$=Panel=$panelno$=.java"?>
package com.powersurgepub.clubplanner.view;

  import com.powersurgepub.clubplanner.*;
  import com.powersurgepub.clubplanner.model.*;
  import com.powersurgepub.psdatalib.clubplanner.*;
  import com.powersurgepub.psdatalib.ui.*;
  import java.awt.*;
  import java.util.*;
  import javax.swing.*;
  
/**
 A panel displaying some of an item's fields, and allowing the user to modify those fields.
 
 Generated by PSTextMerge using =$templatefilename$=.

 @author Herb Bowie
 */
public class =$itemclass$=Panel=$panelno$= 
		extends 
			JPanel 
		implements
			DateOwner {
			
<?include "../includes/=$itemclass$=Panel=$panelno$=-panel-definitions.java"?>

  private     JLabel              bottomFiller   = new JLabel("");

  private     boolean             modified = false;

	private     GridBagger          gb = new GridBagger();
	
	private     JFrame              frame;

  /**
   The constructor.
   */
  public =$itemclass$=Panel=$panelno$=(JFrame frame) {
  
    this.frame = frame;
    gb.startLayout (this, 4, 99);
    gb.setByRows(true);
		gb.setDefaultColumnWeight (0.5);
		gb.setDefaultRowWeight (0.0);
		gb.setAllInsets (4);
    gb.setFill(GridBagConstraints.HORIZONTAL);
    gb.setAnchor(GridBagConstraints.NORTHWEST);

<?include "../includes/=$itemclass$=Panel=$panelno$=-panel-layout.java"?>

    gb.setWidth(2);
    gb.setFill(GridBagConstraints.BOTH);
    gb.setColumnWeight(1.0);
    gb.setRowWeight(0.1);    
    gb.add(bottomFiller);
    
  }  
  
<?include "../includes/=$itemclass$=Panel=$panelno$=-panel-display.java"?>

<?include "../includes/=$itemclass$=Panel=$panelno$=-panel-mod.java"?>

<?include "../includes/=$itemclass$=Panel=$panelno$=-panel-get.java"?>

  /**
   To be called whenever the date is modified by DatePanel.
   */
  public void dateModified (Date date) {
  
  }
  
  /**
   Does this date have an associated rule for recurrence?
   */
  public boolean canRecur() {
    return false;
	}
  
  /**
   Provide a text string describing the recurrence rule, that can
   be used as a tool tip.
   */
  public String getRecurrenceRule() {
    return "";
  }
  
  /**
   Apply the recurrence rule to the date.
   
   @param date Date that will be incremented. 
   */
  public void recur (GregorianCalendar date) {
  
  }

}
<?endif?>
<?endif?>
<?loop?>
