<?nextrec?>
<?definegroup 1 =$itemclass$= ?>
<?definegroup 2 =$panelno$= ?>
<?ifendgroup 2 ?>
<?ifendgroup 1 ?>
<?ifnewgroup 1 ?>
<?ifnewgroup 2 ?>
<?if =$panelno$= ?>
<?output "../includes/=$itemclass$=Panel=$panelno$=-panel-layout.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
  
<?endif?>
<?endif?>
<?if =$panelno$= ?>
<?if =$panelclass$= == "JTextArea" ?>
    =$field&clul$=Label.setLabelFor(=$field&clul$==$panelclass$=);
    gb.setColumnWeight(0.0);
    gb.add(=$field&clul$=Label);
    =$field&clul$==$panelclass$=.setColumns(20);
    =$field&clul$==$panelclass$=.setLineWrap(true);
    =$field&clul$==$panelclass$=.setRows(5);
    =$field&clul$==$panelclass$=.setWrapStyleWord(true);
    =$field&clul$=ScrollPane.setViewportView(=$field&clul$==$panelclass$=);
    gb.add(=$field&clul$=ScrollPane);
<?else?>
    =$field&clul$=Label.setLabelFor(=$field&clul$==$panelclass$=);
    gb.setColumnWeight(0.0);
    gb.add(=$field&clul$=Label);
    gb.add(=$field&clul$==$panelclass$=);
<?endif?>
<?endif?>
<?loop?>
