<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
<?if =$masteritemtype$= = "Master" ?>
      -1 };
<?endif?>
<?ifnewgroup 1 ?>
<?set masterItemType = =$itemtype$= ?>
<?if =$itemtype$= = "Master" ?>
<?output "../includes/=$itemclass$=-master-list-columns.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
 
 private int[] columns = new int[] {
<?endif?>
<?endif?>
<?if =$itemtype$= = "Master" ?>
      =$no$=,
<?endif?>
<?loop?>
