<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
<?if =$holditemtype$= eq Master ?>
      if (match) {
        found = true;
      } else {
        index++;
      }
    }
    if (found) {
      return index;
    } else {
      return -1;
    }
  }
<?endif?>
<?endif?>
<?ifnewgroup 1 ?>
<?set holditemtype = =$itemtype$= ?>
<?if =$itemtype$= eq Master ?>
<?output "../includes/=$itemclass$=-master-list-findByUniqueKey.java"?>

 /**
   Find the matching item, based on its unique key, if it exists in the list. 
   This code was generated by PSTextMerge using template =$templatefilename$= 
   with data file =$datafilename$=.

   @param find=$itemclass$= Master item we are looking for.
   @return Index pointing to the found item, or -1 if not found. 
   */
  public int findByUniqueKey (=$itemclass$= find=$itemclass$=) {
    int index = 0;
    boolean found = false;
    =$itemclass$= current=$itemclass$=;
    while ((! found) && (index < size())) {
      current=$itemclass$= = get (index);
      boolean match = true;
<?endif?>
<?endif?>
<?if =$itemtype$= eq "Master" ?>
<?if =$key$= ?>
      if (find=$itemclass$=.get=$field&cuul$=() == null
          && current=$itemclass$=.get=$field&cuul$=() == null) {
        match = true;
      }
      else
      if (find=$itemclass$=.get=$field&cuul$=() == null
          || current=$itemclass$=.get=$field&cuul$=() == null) {
        match = false;
      } else {
<?if =$case$= != "Ignore" ?>
        match = 
          (find=$itemclass$=.get=$field&cuul$=().equals
            (current=$itemclass$=.get=$field&cuul$=()));
<?endif?>
<?if =$case$= == "Ignore" ?>
        match = 
          (find=$itemclass$=.get=$field&cuul$=AsString().equalsIgnoreCase
            (current=$itemclass$=.get=$field&cuul$=AsString()));
<?endif?>
			}
<?endif?>
<?endif?>
<?loop?>
