<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
<?ifnewgroup 1 ?>
<?if =$itemtype$= = "Master" ?>
<?set masterItemClass = =$itemclass$= ?>
<?output "../includes/=$itemclass$=-master-detail-definitions.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
 
<?endif?>
<?if =$itemtype$= = "Detail" ?>

  /** Master-detail list for =$itemclass$=s. */
  private ArrayList<=$itemclass$=> =$itemclass&clul$=List = new ArrayList();
<?endif?>
<?endif?>
<?loop?>
