<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
  }
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-merge.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
<?set columnCount = 0 ?>
  
  /**
     Merges the contents of a second item into this one.
   */
  public void merge (=$itemclass$= =$itemclass&clul$=2) {
    Object obj2;
    String str2;
<?endif?>
    obj2 = =$itemclass&clul$=2.get=$field&cuul$=();
    if (obj2 == null) {
      // No value available -- leave current value as-is
    } else {
      str2 = obj2.toString();
      if (str2.equals ("")) {
        // No value available -- leave current value as-is
      } else {
        set=$field&cuul$= ((=$fieldclass$=)obj2);
      }
    }
<?set columnCount ++ ?>
<?loop?>
