<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
    }
  }
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-setColumnValue.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
 
<?set columnCount = 0 ?>
  
 /**
  Sets the column value indicated by the given column index. 
  
  @param columnIndex An integer indicating the desired column whose value is to 
                     be set. 
  @param columnValue A string representing the value to be set. 
  */
  public void setColumnValue (int columnIndex, String columnValue) {
    switch (columnIndex) {
<?endif?>
      case =$field&c_uuu$=_COLUMN_INDEX: 
          set=$field&cuul$= (columnValue);
          break;
<?set columnCount ++ ?>
<?loop?>
