<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>
<?if =$tagsField$= == "none" ?>

  /**
   Does this class have a Tags field?
   
   @return True if so, false if not.
   */
  public static boolean isClassTagged() {
    return false;
  }
  
  /**
   Return the tags assigned to this taggable item. 
   
   @return The tags assigned. 
   */
  public Tags getTags () {
    // No Tags field for this item
    return null;
  }
  
  /**
   Flatten all the tags for this item, separating each level/word into its own
   first-level tag.
   */
  public void flattenTags() {
    // No Tags field for this item
  }

  /**
   Convert the tags to all lower-case letters.
   */
  public void lowerCaseTags (){
    // No Tags field for this item
  }
  
  /**
   Set the first TagsNode occurrence for this Taggable item. This is stored
   in a TagsModel occurrence.

   @param tagsNode The tags node to be stored.
   */
  public void setTagsNode (TagsNode tagsNode) {
    // No Tags field for this item
  }

  /**
   Return the first TagsNode occurrence for this Taggable item. These nodes
   are stored in a TagsModel occurrence.

   @return The tags node stored. 
   */
  public TagsNode getTagsNode () {
    // No Tags field for this item
    return null;
  }
<?endif?>
<?if =$tagsField$= != "none" ?>

  /**
   Does this class have a Tags field?
   
   @return True if so, false if not.
   */
  public static boolean isClassTagged() {
    return true;
  }
  
  /**
   Return the tags assigned to this taggable item. 
   
   @return The tags assigned. 
   */
  public Tags getTags () {
    return =$tagsField&clul$=;
  }
  
  /**
   Flatten all the tags for this item, separating each level/word into its own
   first-level tag.
   */
  public void flattenTags() {
    =$tagsField&clul$=.flatten();
  }

  /**
   Convert the tags to all lower-case letters.
   */
  public void lowerCaseTags () {
    =$tagsField&clul$=.makeLowerCase();
  }
  
  /**
   Set the first TagsNode occurrence for this Taggable item. This is stored
   in a TagsModel occurrence.

   @param tagsNode The tags node to be stored.
   */
  public void setTagsNode (TagsNode tagsNode) {
    this.tagsNode = tagsNode;
  }

  /**
   Return the first TagsNode occurrence for this Taggable item. These nodes
   are stored in a TagsModel occurrence.

   @return The tags node stored. 
   */
  public TagsNode getTagsNode (){
    return tagsNode;
  }
<?endif?>
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-taggable-methods.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
 
<?set tagsField = "none" ?>
<?endif?>
<?if "=$fieldclass$=" == "Tags" ?>
<?set tagsField = =$field$= ?>
<?endif?>
<?loop?>
