<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>

    return str.toString();
  }
<?endif?>
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-toString.java"?>

  /**
    Return a string value representing the given item. 
   
    This method generated by PSTextMerge using template =$templatefilename$=.
    
    @return The string by which this item shall be known. 

   */
  public String toString() {

    StringBuilder str = new StringBuilder();
<?endif?>
<?if =$tostring$= ?>
    str.append(get=$field&cuul$=().toString());
<?endif?>
<?loop?>
