<?nextrec?>
<?definegroup 1 =$itemclass$=?>
<?ifendgroup 1 ?>

  public static final int COLUMN_COUNT = =$columnCount$=;
<?ifnewgroup 1 ?>
<?output "../includes/=$itemclass$=-variable-definitions.java"?>

  /* 
   Following code generated by PSTextMerge using: 
   
     template:  =$templatefilename$=
     data file: =$datafilename$=
   */
 
<?set columnCount = 0 ?>
<?endif?>

  /** 
   =$description$= 
   */
<?if "=$fieldclass$=" = "Tags" ?>
  private =$fieldclass$= =$field&clul$= = new =$fieldclass$=();
  
<?else?>
  private =$fieldclass$= =$field&clul$= = null;
  
<?endif?>
  public static final String =$field&c_uuu$=_FIELD_NAME = "=$field$=";
  
  public static final String =$field&c_uuu$=_COLUMN_NAME = "=$briefname$=";
  
  public static final String =$field&c_uuu$=_COMMON_NAME = "=$field&clll$=";
  
  public static final int =$field&c_uuu$=_COLUMN_INDEX = =$columncount$=;
  
  public static final int =$field&c_uuu$=_COLUMN_WIDTH = =$width$=;
  
<?if "=$fieldclass$=" = "Tags" ?>
  private TagsNode tagsNode = null;
<?endif?>
<?set columnCount ++ ?>
<?loop?>
